name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # needed to create releases

jobs:
  build-amd64:
    name: Build x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history including all tags

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename binary for release
        run: cp target/x86_64-unknown-linux-gnu/release/ntfy-log target/x86_64-unknown-linux-gnu/release/ntfy-log-x86_64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ntfy-log-x86_64
          path: target/x86_64-unknown-linux-gnu/release/ntfy-log-x86_64

  build-arm64:
    name: Build aarch64-unknown-linux-gnu
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Build binary
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Rename binary for release
        run: cp target/aarch64-unknown-linux-gnu/release/ntfy-log target/aarch64-unknown-linux-gnu/release/ntfy-log-arm64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ntfy-log-arm64
          path: target/aarch64-unknown-linux-gnu/release/ntfy-log-arm64

  release:
    name: Create GitHub Release
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect commit messages since last tag
        id: changelog
        run: |
          # Ensure we have all tags and full history
          git fetch --tags --force || true
          git fetch --unshallow || git fetch --depth=1000 || true

          # Get the current tag
          current_tag="${GITHUB_REF_NAME}"
          echo "Current tag: $current_tag"

          # Get all tags for debugging
          echo "All tags available:"
          git tag -l --sort=-version:refname

          # Get the previous tag (excluding the current one)
          prev_tag=$(git tag -l --sort=-version:refname | grep -v "^${current_tag}$" | head -n 1)
          echo "Previous tag: $prev_tag"

          if [ -z "$prev_tag" ]; then
            echo "ERROR: No previous tag found in existing repository!"
            exit 1
          fi

          echo "Generating changelog from $prev_tag to $current_tag"
          # Get actual commit hashes for the tags
          prev_tag_hash=$(git rev-list -n 1 $prev_tag)
          current_tag_hash=$(git rev-list -n 1 $current_tag)
          echo "Previous tag hash: $prev_tag_hash"
          echo "Current tag hash: $current_tag_hash"

          # Verify the commits exist in our repository
          if ! git cat-file -e "$prev_tag_hash" 2>/dev/null; then
            echo "ERROR: Previous tag commit $prev_tag_hash not found in repository"
            exit 1
          fi
          if ! git cat-file -e "$current_tag_hash" 2>/dev/null; then
            echo "ERROR: Current tag commit $current_tag_hash not found in repository"
            exit 1
          fi

          # Get commits between tags, exclude version-only commit messages
          notes=$(git log "${prev_tag_hash}..${current_tag_hash}^" --pretty=format:"- %s" --reverse | grep -v -E "^- [0-9]+\.[0-9]+\.[0-9]+$")

          # If notes is empty, add a default message
          if [ -z "$notes" ]; then
            notes="- Release $current_tag"
          fi

          echo "Final changelog:"
          echo "$notes"

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$notes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files (debug)
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.notes }}
          files: |
            artifacts/ntfy-log-x86_64/ntfy-log-x86_64
            artifacts/ntfy-log-arm64/ntfy-log-arm64
